### ISSUE TITLE
[v3]loginWithOauth issue on Safari when using popup as uxMode 

### ISSUE THREAD

**Issue by AyushBherwani1998** [Web3Auth/mpc-core-kit#154] opened 2024-06-06 07:09 UTC
## Description 

Not able to login in Safari browser when using loginWithOauth with popup as uxMode. It initiates the login, and after login, it's not able to redirect properly. On the other hand, same works fine on the Chrome browser. 

## Screen-recording 

https://github.com/Web3Auth/mpc-core-kit/assets/34301187/855cf289-5321-4d9b-a292-ba90f0c7d460

**Comment by AyushBherwani1998** [comment] 2024-06-06 09:54
The error in the console of popup:

```
WebSocket connection to 'wss://broadcast-server.tor.us/socket.io/?EIO=4&transport=websocket' failed: WebSocket is closed due to suspension.
```

**Comment by matthiasgeihs** [comment] 2024-07-09 07:13
Seems to be related to an issue with the service worker in [CustomAuth](https://github.com/torusresearch/CustomAuth/tree/master).

**Comment by metalurgical** [comment] 2024-07-09 08:03
If no problem can be found anywhere else this might be related to a bug resurfacing in safari.

Are you running the latest version, or perhaps an older versions?

It has been patched at least twice before:
https://bugs.webkit.org/show_bug.cgi?id=143513
https://bugs.webkit.org/show_bug.cgi?id=228329

**Comment by matthiasgeihs** [comment] 2024-07-09 09:30
Update:
The issue is not in `mpc-core-kit`, neither in `CustomAuth`. The issue was that in order to use the popup flow, additional service worker worker code ([sw.js](https://github.com/torusresearch/CustomAuth/blob/89fa7c77af78457d12744dec6f9c1472e99052f7/serviceworker/sw.js)) needs to be served with the app. However, this code was not updated in the example. Fixed in https://github.com/Web3Auth/web3auth-core-kit-examples/pull/607.

**Closed by matthiasgeihs** 2024-07-09 09:30 UTC

**Comment by metalurgical** [comment] 2024-07-09 09:39
Nice find!

**Comment by matthiasgeihs** [comment] 2024-07-09 09:40
Credits go to @ieow ;)
